/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CosmeticsRouteImport } from './routes/cosmetics'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ApiDiscordRouteImport } from './routes/api/discord'
import { Route as ApiLeaderboardRouteImport } from './routes/api/leaderboard'
import { Route as ApiMcLinkRouteImport } from './routes/api/mc-link'
import { Route as PlayerUsernameRouteImport } from './routes/player.$username'
import { Route as ApiAdminOrdersRouteImport } from './routes/api/admin/orders'
import { Route as ApiAdminPlayersRouteImport } from './routes/api/admin/players'
import { Route as ApiAdminSupportRouteImport } from './routes/api/admin/support'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthVerifyEmailRouteImport } from './routes/api/auth/verify-email'
import { Route as ApiPlayerUsernameRouteImport } from './routes/api/player.$username'
import { Route as ApiSettingsAnnouncementRouteImport } from './routes/api/settings/announcement'
import { Route as ApiStoreCheckoutRouteImport } from './routes/api/store/checkout'
import { Route as ApiStoreWebhookRouteImport } from './routes/api/store/webhook'
import { Route as ApiSupportTicketsRouteImport } from './routes/api/support/tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmeticsRoute = CosmeticsRouteImport.update({
  id: '/cosmetics',
  path: '/cosmetics',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordRoute = ApiDiscordRouteImport.update({
  id: '/api/discord',
  path: '/api/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardRoute = ApiLeaderboardRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcLinkRoute = ApiMcLinkRouteImport.update({
  id: '/api/mc-link',
  path: '/api/mc-link',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerUsernameRoute = PlayerUsernameRouteImport.update({
  id: '/player/$username',
  path: '/player/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersRoute = ApiAdminOrdersRouteImport.update({
  id: '/api/admin/orders',
  path: '/api/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPlayersRoute = ApiAdminPlayersRouteImport.update({
  id: '/api/admin/players',
  path: '/api/admin/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSupportRoute = ApiAdminSupportRouteImport.update({
  id: '/api/admin/support',
  path: '/api/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyEmailRoute = ApiAuthVerifyEmailRouteImport.update({
  id: '/api/auth/verify-email',
  path: '/api/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerUsernameRoute = ApiPlayerUsernameRouteImport.update({
  id: '/api/player/$username',
  path: '/api/player/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsAnnouncementRoute = ApiSettingsAnnouncementRouteImport.update({
  id: '/api/settings/announcement',
  path: '/api/settings/announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreCheckoutRoute = ApiStoreCheckoutRouteImport.update({
  id: '/api/store/checkout',
  path: '/api/store/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreWebhookRoute = ApiStoreWebhookRouteImport.update({
  id: '/api/store/webhook',
  path: '/api/store/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportTicketsRoute = ApiSupportTicketsRouteImport.update({
  id: '/api/support/tickets',
  path: '/api/support/tickets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cosmetics': typeof CosmeticsRoute
  '/discord': typeof DiscordRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/rankings': typeof RankingsRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/api/discord': typeof ApiDiscordRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/mc-link': typeof ApiMcLinkRoute
  '/player/$username': typeof PlayerUsernameRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/players': typeof ApiAdminPlayersRoute
  '/api/admin/support': typeof ApiAdminSupportRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/player/$username': typeof ApiPlayerUsernameRoute
  '/api/settings/announcement': typeof ApiSettingsAnnouncementRoute
  '/api/store/checkout': typeof ApiStoreCheckoutRoute
  '/api/store/webhook': typeof ApiStoreWebhookRoute
  '/api/support/tickets': typeof ApiSupportTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cosmetics': typeof CosmeticsRoute
  '/discord': typeof DiscordRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/rankings': typeof RankingsRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/api/discord': typeof ApiDiscordRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/mc-link': typeof ApiMcLinkRoute
  '/player/$username': typeof PlayerUsernameRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/players': typeof ApiAdminPlayersRoute
  '/api/admin/support': typeof ApiAdminSupportRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/player/$username': typeof ApiPlayerUsernameRoute
  '/api/settings/announcement': typeof ApiSettingsAnnouncementRoute
  '/api/store/checkout': typeof ApiStoreCheckoutRoute
  '/api/store/webhook': typeof ApiStoreWebhookRoute
  '/api/support/tickets': typeof ApiSupportTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cosmetics': typeof CosmeticsRoute
  '/discord': typeof DiscordRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/rankings': typeof RankingsRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/api/discord': typeof ApiDiscordRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/mc-link': typeof ApiMcLinkRoute
  '/player/$username': typeof PlayerUsernameRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/players': typeof ApiAdminPlayersRoute
  '/api/admin/support': typeof ApiAdminSupportRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/player/$username': typeof ApiPlayerUsernameRoute
  '/api/settings/announcement': typeof ApiSettingsAnnouncementRoute
  '/api/store/checkout': typeof ApiStoreCheckoutRoute
  '/api/store/webhook': typeof ApiStoreWebhookRoute
  '/api/support/tickets': typeof ApiSupportTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cosmetics'
    | '/discord'
    | '/leaderboards'
    | '/login'
    | '/rankings'
    | '/store'
    | '/support'
    | '/api/discord'
    | '/api/leaderboard'
    | '/api/mc-link'
    | '/player/$username'
    | '/api/admin/orders'
    | '/api/admin/players'
    | '/api/admin/support'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/verify-email'
    | '/api/player/$username'
    | '/api/settings/announcement'
    | '/api/store/checkout'
    | '/api/store/webhook'
    | '/api/support/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/cosmetics'
    | '/discord'
    | '/leaderboards'
    | '/login'
    | '/rankings'
    | '/store'
    | '/support'
    | '/api/discord'
    | '/api/leaderboard'
    | '/api/mc-link'
    | '/player/$username'
    | '/api/admin/orders'
    | '/api/admin/players'
    | '/api/admin/support'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/verify-email'
    | '/api/player/$username'
    | '/api/settings/announcement'
    | '/api/store/checkout'
    | '/api/store/webhook'
    | '/api/support/tickets'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cosmetics'
    | '/discord'
    | '/leaderboards'
    | '/login'
    | '/rankings'
    | '/store'
    | '/support'
    | '/api/discord'
    | '/api/leaderboard'
    | '/api/mc-link'
    | '/player/$username'
    | '/api/admin/orders'
    | '/api/admin/players'
    | '/api/admin/support'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/verify-email'
    | '/api/player/$username'
    | '/api/settings/announcement'
    | '/api/store/checkout'
    | '/api/store/webhook'
    | '/api/support/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CosmeticsRoute: typeof CosmeticsRoute
  DiscordRoute: typeof DiscordRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  LoginRoute: typeof LoginRoute
  RankingsRoute: typeof RankingsRoute
  StoreRoute: typeof StoreRoute
  SupportRoute: typeof SupportRoute
  ApiDiscordRoute: typeof ApiDiscordRoute
  ApiLeaderboardRoute: typeof ApiLeaderboardRoute
  ApiMcLinkRoute: typeof ApiMcLinkRoute
  PlayerUsernameRoute: typeof PlayerUsernameRoute
  ApiAdminOrdersRoute: typeof ApiAdminOrdersRoute
  ApiAdminPlayersRoute: typeof ApiAdminPlayersRoute
  ApiAdminSupportRoute: typeof ApiAdminSupportRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthVerifyEmailRoute: typeof ApiAuthVerifyEmailRoute
  ApiPlayerUsernameRoute: typeof ApiPlayerUsernameRoute
  ApiSettingsAnnouncementRoute: typeof ApiSettingsAnnouncementRoute
  ApiStoreCheckoutRoute: typeof ApiStoreCheckoutRoute
  ApiStoreWebhookRoute: typeof ApiStoreWebhookRoute
  ApiSupportTicketsRoute: typeof ApiSupportTicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmetics': {
      id: '/cosmetics'
      path: '/cosmetics'
      fullPath: '/cosmetics'
      preLoaderRoute: typeof CosmeticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord': {
      id: '/api/discord'
      path: '/api/discord'
      fullPath: '/api/discord'
      preLoaderRoute: typeof ApiDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mc-link': {
      id: '/api/mc-link'
      path: '/api/mc-link'
      fullPath: '/api/mc-link'
      preLoaderRoute: typeof ApiMcLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$username': {
      id: '/player/$username'
      path: '/player/$username'
      fullPath: '/player/$username'
      preLoaderRoute: typeof PlayerUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders': {
      id: '/api/admin/orders'
      path: '/api/admin/orders'
      fullPath: '/api/admin/orders'
      preLoaderRoute: typeof ApiAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/players': {
      id: '/api/admin/players'
      path: '/api/admin/players'
      fullPath: '/api/admin/players'
      preLoaderRoute: typeof ApiAdminPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/support': {
      id: '/api/admin/support'
      path: '/api/admin/support'
      fullPath: '/api/admin/support'
      preLoaderRoute: typeof ApiAdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-email': {
      id: '/api/auth/verify-email'
      path: '/api/auth/verify-email'
      fullPath: '/api/auth/verify-email'
      preLoaderRoute: typeof ApiAuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/$username': {
      id: '/api/player/$username'
      path: '/api/player/$username'
      fullPath: '/api/player/$username'
      preLoaderRoute: typeof ApiPlayerUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/announcement': {
      id: '/api/settings/announcement'
      path: '/api/settings/announcement'
      fullPath: '/api/settings/announcement'
      preLoaderRoute: typeof ApiSettingsAnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/checkout': {
      id: '/api/store/checkout'
      path: '/api/store/checkout'
      fullPath: '/api/store/checkout'
      preLoaderRoute: typeof ApiStoreCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/webhook': {
      id: '/api/store/webhook'
      path: '/api/store/webhook'
      fullPath: '/api/store/webhook'
      preLoaderRoute: typeof ApiStoreWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support/tickets': {
      id: '/api/support/tickets'
      path: '/api/support/tickets'
      fullPath: '/api/support/tickets'
      preLoaderRoute: typeof ApiSupportTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CosmeticsRoute: CosmeticsRoute,
  DiscordRoute: DiscordRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  LoginRoute: LoginRoute,
  RankingsRoute: RankingsRoute,
  StoreRoute: StoreRoute,
  SupportRoute: SupportRoute,
  ApiDiscordRoute: ApiDiscordRoute,
  ApiLeaderboardRoute: ApiLeaderboardRoute,
  ApiMcLinkRoute: ApiMcLinkRoute,
  PlayerUsernameRoute: PlayerUsernameRoute,
  ApiAdminOrdersRoute: ApiAdminOrdersRoute,
  ApiAdminPlayersRoute: ApiAdminPlayersRoute,
  ApiAdminSupportRoute: ApiAdminSupportRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthVerifyEmailRoute: ApiAuthVerifyEmailRoute,
  ApiPlayerUsernameRoute: ApiPlayerUsernameRoute,
  ApiSettingsAnnouncementRoute: ApiSettingsAnnouncementRoute,
  ApiStoreCheckoutRoute: ApiStoreCheckoutRoute,
  ApiStoreWebhookRoute: ApiStoreWebhookRoute,
  ApiSupportTicketsRoute: ApiSupportTicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
